services:
- type: web
  name: crypto-signal-api
  env: docker
  plan: starter
  healthCheckPath: /health
  envVars:
    - key: API_KEY
      sync: false
    - key: TG_BOT_TOKEN
      sync: false
    - key: TG_CHAT_ID
      sync: false
    - key: NEWS_API_KEY
      sync: false
    - key: CRYPTOPANIC_API_KEY
      sync: false
    - key: CACHE_ENABLED
      value: "true"
    - key: ENVIRONMENT
      value: "production"
    - key: DEBUG
      value: "false"
    - key: REDIS_URL
      fromService:
        type: redis
        name: crypto-redis
    - key: DATABASE_URL
      fromService:
        type: pserv
        name: crypto-signal-db

databases:
- name: crypto-redis
  plan: free
- name: crypto-signal-db
  plan: free
